//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserCenterSystem.UserInfo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://UserInfo.org/", ConfigurationName="UserInfo.UserInfoSoap")]
    public interface UserInfoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UserCenterSystem.UserInfo.GetUserInfoResponse GetUserInfo(UserCenterSystem.UserInfo.GetUserInfoRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<UserCenterSystem.UserInfo.GetUserInfoResponse> GetUserInfoAsync(UserCenterSystem.UserInfo.GetUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetInferConfig", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetInferConfig(string LoginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetInferConfig", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetInferConfigAsync(string LoginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetUserInfoByLoginName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UserCenterSystem.UserInfo.GetUserInfoByLoginNameResponse GetUserInfoByLoginName(UserCenterSystem.UserInfo.GetUserInfoByLoginNameRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetUserInfoByLoginName", ReplyAction="*")]
        System.Threading.Tasks.Task<UserCenterSystem.UserInfo.GetUserInfoByLoginNameResponse> GetUserInfoByLoginNameAsync(UserCenterSystem.UserInfo.GetUserInfoByLoginNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/IsAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsAdmin(string LoginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/IsAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsAdminAsync(string LoginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetJYZ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetJYZ();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetJYZ", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetJYZAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetTeacherInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTeacherInfo(string UserLoginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetTeacherInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTeacherInfoAsync(string UserLoginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetStudentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetStudentInfo(string UserLoginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UserInfo.org/GetStudentInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetStudentInfoAsync(string UserLoginName);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfo", WrapperNamespace="http://UserInfo.org/", IsWrapped=true)]
    public partial class GetUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=0)]
        public string LoginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=1)]
        public string[] ColumnTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=3)]
        public string strTableName;
        
        public GetUserInfoRequest() {
        }
        
        public GetUserInfoRequest(string LoginName, string[] ColumnTitle, string SchoolCode, string strTableName) {
            this.LoginName = LoginName;
            this.ColumnTitle = ColumnTitle;
            this.SchoolCode = SchoolCode;
            this.strTableName = strTableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfoResponse", WrapperNamespace="http://UserInfo.org/", IsWrapped=true)]
    public partial class GetUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=0)]
        public System.Data.DataTable GetUserInfoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=1)]
        public string strResult;
        
        public GetUserInfoResponse() {
        }
        
        public GetUserInfoResponse(System.Data.DataTable GetUserInfoResult, string strResult) {
            this.GetUserInfoResult = GetUserInfoResult;
            this.strResult = strResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfoByLoginName", WrapperNamespace="http://UserInfo.org/", IsWrapped=true)]
    public partial class GetUserInfoByLoginNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=0)]
        public string LoginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=1)]
        public string[] ColumnTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=2)]
        public string strUserLoginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=3)]
        public string strTableName;
        
        public GetUserInfoByLoginNameRequest() {
        }
        
        public GetUserInfoByLoginNameRequest(string LoginName, string[] ColumnTitle, string strUserLoginName, string strTableName) {
            this.LoginName = LoginName;
            this.ColumnTitle = ColumnTitle;
            this.strUserLoginName = strUserLoginName;
            this.strTableName = strTableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfoByLoginNameResponse", WrapperNamespace="http://UserInfo.org/", IsWrapped=true)]
    public partial class GetUserInfoByLoginNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=0)]
        public System.Data.DataTable GetUserInfoByLoginNameResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UserInfo.org/", Order=1)]
        public string strResult;
        
        public GetUserInfoByLoginNameResponse() {
        }
        
        public GetUserInfoByLoginNameResponse(System.Data.DataTable GetUserInfoByLoginNameResult, string strResult) {
            this.GetUserInfoByLoginNameResult = GetUserInfoByLoginNameResult;
            this.strResult = strResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserInfoSoapChannel : UserCenterSystem.UserInfo.UserInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserInfoSoapClient : System.ServiceModel.ClientBase<UserCenterSystem.UserInfo.UserInfoSoap>, UserCenterSystem.UserInfo.UserInfoSoap {
        
        public UserInfoSoapClient() {
        }
        
        public UserInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UserCenterSystem.UserInfo.GetUserInfoResponse UserCenterSystem.UserInfo.UserInfoSoap.GetUserInfo(UserCenterSystem.UserInfo.GetUserInfoRequest request) {
            return base.Channel.GetUserInfo(request);
        }
        
        public System.Data.DataTable GetUserInfo(string LoginName, string[] ColumnTitle, string SchoolCode, string strTableName, out string strResult) {
            UserCenterSystem.UserInfo.GetUserInfoRequest inValue = new UserCenterSystem.UserInfo.GetUserInfoRequest();
            inValue.LoginName = LoginName;
            inValue.ColumnTitle = ColumnTitle;
            inValue.SchoolCode = SchoolCode;
            inValue.strTableName = strTableName;
            UserCenterSystem.UserInfo.GetUserInfoResponse retVal = ((UserCenterSystem.UserInfo.UserInfoSoap)(this)).GetUserInfo(inValue);
            strResult = retVal.strResult;
            return retVal.GetUserInfoResult;
        }
        
        public System.Threading.Tasks.Task<UserCenterSystem.UserInfo.GetUserInfoResponse> GetUserInfoAsync(UserCenterSystem.UserInfo.GetUserInfoRequest request) {
            return base.Channel.GetUserInfoAsync(request);
        }
        
        public System.Data.DataTable GetInferConfig(string LoginName) {
            return base.Channel.GetInferConfig(LoginName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetInferConfigAsync(string LoginName) {
            return base.Channel.GetInferConfigAsync(LoginName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UserCenterSystem.UserInfo.GetUserInfoByLoginNameResponse UserCenterSystem.UserInfo.UserInfoSoap.GetUserInfoByLoginName(UserCenterSystem.UserInfo.GetUserInfoByLoginNameRequest request) {
            return base.Channel.GetUserInfoByLoginName(request);
        }
        
        public System.Data.DataTable GetUserInfoByLoginName(string LoginName, string[] ColumnTitle, string strUserLoginName, string strTableName, out string strResult) {
            UserCenterSystem.UserInfo.GetUserInfoByLoginNameRequest inValue = new UserCenterSystem.UserInfo.GetUserInfoByLoginNameRequest();
            inValue.LoginName = LoginName;
            inValue.ColumnTitle = ColumnTitle;
            inValue.strUserLoginName = strUserLoginName;
            inValue.strTableName = strTableName;
            UserCenterSystem.UserInfo.GetUserInfoByLoginNameResponse retVal = ((UserCenterSystem.UserInfo.UserInfoSoap)(this)).GetUserInfoByLoginName(inValue);
            strResult = retVal.strResult;
            return retVal.GetUserInfoByLoginNameResult;
        }
        
        public System.Threading.Tasks.Task<UserCenterSystem.UserInfo.GetUserInfoByLoginNameResponse> GetUserInfoByLoginNameAsync(UserCenterSystem.UserInfo.GetUserInfoByLoginNameRequest request) {
            return base.Channel.GetUserInfoByLoginNameAsync(request);
        }
        
        public bool IsAdmin(string LoginName) {
            return base.Channel.IsAdmin(LoginName);
        }
        
        public System.Threading.Tasks.Task<bool> IsAdminAsync(string LoginName) {
            return base.Channel.IsAdminAsync(LoginName);
        }
        
        public System.Data.DataTable GetJYZ() {
            return base.Channel.GetJYZ();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetJYZAsync() {
            return base.Channel.GetJYZAsync();
        }
        
        public System.Data.DataTable GetTeacherInfo(string UserLoginName) {
            return base.Channel.GetTeacherInfo(UserLoginName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTeacherInfoAsync(string UserLoginName) {
            return base.Channel.GetTeacherInfoAsync(UserLoginName);
        }
        
        public System.Data.DataTable GetStudentInfo(string UserLoginName) {
            return base.Channel.GetStudentInfo(UserLoginName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetStudentInfoAsync(string UserLoginName) {
            return base.Channel.GetStudentInfoAsync(UserLoginName);
        }
    }
}
